connections:
  procs: 1
  memoryLimit: 2GB
metrics:
  procs: 1
  memoryLimit: 2GB
notifications:
  procs: 1
  memoryLimit: 2GB
search:
  procs: 1
  memoryLimit: 2GB
stream_connections:
  procs: 0
  autoScale: true
  memoryLimit: 2GB
edge_connections:
  procs: 0
  autoScale: true
  memoryLimit: 2GB
connection_proxy:
  procs: 0
  memoryLimit: 2GB
